kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: oracle-db
spec:
  finalizers:
    - kubernetes
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oracle-db
  namespace: oracle-db
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
        deployment: oracle-db
    spec:
      containers:
        - name: oracle-db
          image: docker.io/amarmane9999/oracle-db
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ORACLE_SID
              value: orcl1
            - name: ORACLE_PWD
              value: orcl2
            - name: ORACLE_PDB
              value: orcl3
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
      serviceAccountName: oracle-sa
      serviceAccount: oracle-sa
      securityContext:
        runAsUser: 54321
---
kind: Service
apiVersion: v1
metadata:
  name: oracle-db
  namespace: oracle-db
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: oracle-db
    deployment: oracle-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oracle-sa
  namespace: oracle-db
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oracle-rl
  namespace: oracle-db
subjects:
  - kind: ServiceAccount
    name: oracle-sa
    namespace: oracle-db
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
