apiVersion: v1
kind: List
items:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: oracle-db
    spec:
      finalizers:
        - kubernetes
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: oracle-sa
      namespace: oracle-db
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: oracle-rl
      namespace: oracle-db
    subjects:
      - kind: ServiceAccount
        name: oracle-sa
        namespace: oracle-db
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: 'system:openshift:scc:anyuid'
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: oracledb
      namespace: oracle-db
      labels:
        app: oracledb
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: oracledb
      template:
        metadata:
          labels:
            app: oracledb
            deployment: oracledb
        spec:
          containers:
            - name: oracledb
              image: docker.io/amarmane9999/oracle-db
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: ORACLE_SID
                  value: orcl1
                - name: ORACLE_PWD
                  value: orcl2
                - name: ORACLE_PDB
                  value: orcl3
              resources:
                limits:
                  cpu: '2'
                  memory: 4Gi
                requests:
                  cpu: '2'
                  memory: 4Gi
              imagePullPolicy: IfNotPresent
          serviceAccountName: oracle-sa
          serviceAccount: oracle-sa
          securityContext:
            runAsUser: 54321
  - kind: Service
    apiVersion: v1
    metadata:
      name: oracledb
      namespace: oracle-db
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: 1521-tcp
          protocol: TCP
          port: 1521
          targetPort: 1521
      selector:
        app: oracledb
        deployment: oracledb
